language: php

addons:
  apt:
    packages:
      - apache2
      - libapache2-mod-php5
      - php5-curl
      - php5-mysql
      - php5-pgsql

matrix:
  include:
    - php: 5.5
      env: DB=mysqli
    - php: 5.6
      env: DB=mysqli
    - php: 7
      env: DB=mysqli
  fast_finish: true

install:
    - if [ "$DB" == "postgres" ]; then psql -c "DROP DATABASE IF EXISTS elkarte_test;" -U postgres; fi;
    - if [ "$DB" == "postgres" ]; then psql -c "create database elkarte_test;" -U postgres; fi;
    - if [ "$DB" == "mysqli" ]; then mysql -e "DROP DATABASE IF EXISTS elkarte_test;" -uroot; fi;
    - if [ "$DB" == "mysqli" ]; then mysql -e "create database IF NOT EXISTS elkarte_test;" -uroot; fi;

before_script:
    - SHORT_PHP=${TRAVIS_PHP_VERSION:0:3}
    - composer install --no-interaction --prefer-source --quiet
    - phpenv config-add /var/www/Build/tests/travis-ci/travis_php.ini
    - if [ "$DB" == "mysqli" ]; then php ./Build/tests/travis-ci/setup_mysql.php; fi;
    - if [ "$DB" == "postgres" ]; then php ./Build/tests/travis-ci/setup_pgsql.php; fi;
    - rm -rf /var/www/Elkarte/src/Admin/Install
    - if [ "$SHORT_PHP" == "5.5" -a "$DB" == "mysqli" ]; then phpenv config-add /var/www/Build/tests/travis-ci/travis_webtest_php.ini; fi;
    - if [ "$SHORT_PHP" == "5.5" -a "$DB" == "mysqli" ]; then ./Build/tests/travis-ci/setup-selenium.sh; fi;

script: 
    - chmod +x /var/www/tests/travis-ci/setup-script.sh
    - /var/www/Build/tests/travis-ci/setup-script.sh $DB $TRAVIS_PHP_VERSION

after_script:
    - chmod +x /var/www/tests/travis-ci/setup-results.sh
    - /var/www/Build/tests/travis-ci/setup-results.sh $DB $TRAVIS_PHP_VERSION

after_failure:
    - chmod +x /var/www/tests/travis-ci/setup-failure.sh
    - /var/www/Build/tests/travis-ci/setup-failure.sh $DB $TRAVIS_PHP_VERSION